services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-lbtig
    environment:
      POSTGRES_USER: kj
      POSTGRES_PASSWORD: 314314
      POSTGRES_DB: rss_podcast
    ports:
      - "5432:5432"  # change to "5433:5432" if 5432 is already used on host
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: valkey-podcast
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: valkey-server --appendonly yes
    restart: unless-stopped

volumes:
  pg-data:
  valkey-data: