services:
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: valkey-podcast
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: valkey-server --appendonly yes
    restart: unless-stopped

volumes:
  valkey-data: